### ISSUE TITLE
Krylov solver "CG" produces incorrect results

### ISSUE THREAD

**Issue by rsmedleystevenson** [UK-MAC/TeaLeaf_Trilinos#2]
Changing the Krylov solver in Belos to "CG" leads erroreous solutions whereas "RCG", "GMRES" and "GCRODR" all produce correct solutions. So far this issue has been observed with version 11.4 and version 11.12, but is believed to be independent of the Trilinos version. This may be down to misunderstanding the settings in Belos and our inexperience with using Trilinos.

**Comment by rsmedleystevenson** [comment]
New branch trilinos-issue has isolated the problem to the initialisation of the residual, which when overidden on line 833 of BelosPseudoBlockCGSolMgr.hpp then matches the other solver implementations. This will be reported to the Trilinos developers.

**Comment by rsmedleystevenson** [comment]
Comparing the output files: output_tril_cg-l  output_tril_cg-r  output_tril_rcg-l  output_tril_rcg-r illustrates the results of left and right preconditioning for the PseudoBlockCG and the RCG Krylov methods.   output_tril_cg-l-mod shows the effect of the fix which corrects the initial value of R_0 which otherwise contains the preconditioned residual and hence the search direction is "doubly" preconditioned.

**Comment by mhoemmen** [comment]
Hi there!  We're working on this in Trilinos.  I saw that you wrote "fix" -- do you have a patch?  It's OK if you don't have one -- I would just prefer to use your patch if you've already tested it in situ.  Thanks!

**Comment by rsmedleystevenson** [comment]
Mark, the fix was to add a recalculation of the residual on line 833 of BelosPseudoBlockCGSolMgr.hpp as per the second comment. This is an extra line absent from the original routine.

**Comment by mhoemmen** [comment]
> Mark, the fix was to add a recalculation of the residual on line 833 of BelosPseudoBlockCGSolMgr.hpp as per the second comment. This is an extra line absent from the original routine.

Could you post here exactly the line of code you added?  I'm comparing to BelosPseudoBlockGMRESSolMgr.hpp and not finding how they differ.

**Comment by rsmedleystevenson** [comment]
```
  // Get the current residual for this block of linear systems.
  Teuchos::RCP<MV> R_0 = MVT::CloneViewNonConst( *(Teuchos::rcp_const_cast<MV>(problem_->getInitResVec())), currIdx );
  problem_->computeCurrResVec( &*R_0 ); // recompute the residual - extra coding for debugging
```

The second line is what I added to the BelosPseudoBlockCGSolMgr.hpp i.e. for CG not GMRES and this is in the file that I added to the trilinos-issue branch of this repository.

**Comment by rsmedleystevenson** [comment]
This goes at line 891 in the current version from the GitHub repository (the file was copied from 12.4). It's possible you fixed this previously? I admit I haven't tested this in version 12.6 or later but it was broken in all previous versions and I couldn't find any commits which looked relevant to the issue.

**Comment by rsmedleystevenson** [comment]
Note that the error is on the second and subsequent solves (not the first one), where we have simply replaced the RHS vector and matrix entry values. As it works with right preconditioning and the RCG solver this is specific to left preconditioning of the PseudoBlockCG iteration.

**Comment by hkthorn** [comment]
When a Belos solver object and linear problem object is being reused for multiple solves, then the solver should be "reset".  That communicates to the solver that another solve is happening and let's them do whatever reinitialization that may be necessary.  So, in between calls to "solve()" (after you changed the linear system values) did you call "reset( Belos::Problem )" to communicate to the solver that the RHS vector and matrix entry values had changed?  That would prompt the solver to compute the correct initial residual from the changed entries in the linear problem.

**Comment by rsmedleystevenson** [comment]
Thanks for the suggestion and for pointing me to the example. I've added a call to reset the solver but it hasn't resolved the issue. Destroying and then recreating the solver does resolve the issue, but that feels like overkill.

**Comment by hkthorn** [comment]
Thanks for trying it out and letting me know!  I'm going to create some preconditioned resolve tests so that I can narrow down the issue.

Heidi

## 

Heidi K. Thornquist
Electrical Models & Simulation
Sandia National Laboratories
Albuquerque, NM  87185-1323

**Comment by rsmedleystevenson** [comment]
I was wrong - even destroying the solver doesn't seem to fix the issue with the left preconditioned pseudo block CG solver.

**Comment by hkthorn** [comment]
Interesting, and not in a good way.

Out of curiosity, if you change the matrix values in between solves, do you also have the preconditioner rebuild itself in between solves before you call "reset" on the solver?

## 

Heidi K. Thornquist
Electrical Models & Simulation
Sandia National Laboratories
Albuquerque, NM  87185-1323

**Comment by rsmedleystevenson** [comment]
Here is the code that sets the preconditioner:

> ```
> // v12.x onwards
> typedef Ifpack2::Preconditioner<> prec_type;
> Teuchos::RCP<prec_type> preconditioner;
> typedef Tpetra::RowMatrix<> row_matrix_type;
> preconditioner = Ifpack2::Factory::create<row_matrix_type> ("DIAGONAL", A);
> preconditioner->initialize ();
> 
> preconditioner->compute ();
> 
> problem->setLeftPrec(preconditioner);
> ```

so it is re-computed even when the matrix doesn't change. I think the problem relates to the value stored in R_0 and that getInitResVec() returns the left preconditioned residual when it should just be the residual itself.

**Comment by hkthorn** [comment]
My confusion is that getInitResVec DOES return the unpreconditioned residual vector:

Teuchos::RCP<const MV> getInitResVec() const { return(R0_); }

If the solver needs the preconditioned residual vector, if it exists, then it would call getInitPrecResVec that returns the preconditioned residual vector:

Teuchos::RCP<const MV> getInitPrecResVec() const { return(PR0_); }

Hopefully you see my confusion.  Are you setting the residual scaling explicitly in the parameter list that you are passing into the solver object because the scaling used by the residual test is also unpreconditioned:

const std::string PseudoBlockCGSolMgr<ScalarType,MV,OP,true>::resScale_default_ = "Norm of Initial Residual";

What is parameter list that you are passing into the solvers?

Thanks,
Heidi

## 

Heidi K. Thornquist
Electrical Models & Simulation
Sandia National Laboratories
Albuquerque, NM  87185-1323

**Comment by rsmedleystevenson** [comment]
I agree this shouldn't be necessary and isn't doing what's advertised, hence my difficulty in making more progress with this issue. Here is the parameter list:

> ```
> Teuchos::RCP<Teuchos::ParameterList> solverParams = Teuchos::parameterList();
> solverParams->set("Maximum Iterations", 1000);
>  // TODO: Tolerance level causing issues at scale??
> solverParams->set("Convergence Tolerance", 1.0e-15); 
> int verbosity = Belos::Errors + Belos::Warnings;
> verbosity += Belos::TimingDetails + Belos::StatusTestDetails;
> verbosity += Belos::IterationDetails + Belos::FinalSummary;
> //verbosity += Belos::Debug;
> solverParams->set("Verbosity", verbosity);
> solverParams->set("Output Frequency", 1);
> solverParams->set("Output Style", (int) Belos::Brief);
> //solverParams->set("Implicit Residual Scaling","None"); // Not the cause of the issues with CG
> 
> //solver = factory.create("RCG", solverParams);
> //solver = factory.create("GMRES", solverParams);
> solver = factory.create("CG", solverParams); // This produces erroneous results
>                                              // when combined with left preconditioning
> std::cout << "DONE." << std::endl;
> 
> std::cout << std::endl << "Parameters available:" << std::endl;
> solver->getValidParameters()->print();
> std::cout << std::endl << "Parameters set:" << std::endl;
> solver->getCurrentParameters()->print();
> ```

and the output:

> Parameters available:
> Convergence Tolerance = 1e-08   [unused]
> Maximum Iterations = 1000   [unused]
> Assert Positive Definiteness = 1   [unused]
> Verbosity = 0   [unused]
> Output Style = 0   [unused]
> Output Frequency = -1   [unused]
> Deflation Quorum = 1   [unused]
> Output Stream = Teuchos::RCPstd::ostream{ptr=0x1472c00,node=0x1963080,strong_count=4,weak_count=0}   [unused]
> Show Maximum Residual Norm Only = 0   [unused]
> Implicit Residual Scaling = Norm of Initial Residual   [unused]
> Estimate Condition Number = 0   [unused]
> Residual Scaling = Norm of Initial Residual   [unused]
> Timer Label = Belos   [unused]
> 
> Parameters set:
> Maximum Iterations = 1000   [unused]
> Verbosity = 59   [unused]
> Output Style = 1   [unused]
> Output Frequency = 1   [unused]
> Convergence Tolerance = 1e-15   [unused]

**Comment by rsmedleystevenson** [comment]
Somehow I think R_0 is being pointed at PR_0 by getInitResVec() and this is the source of the issue. Calling the recompute fixes this but is only a workaround rather than solving the underlying problem.

**Comment by hkthorn** [comment]
Are you using the same linear problem object and switching between unpreconditioned/right-preconditioned solves and left-preconditioned solves?  The PR0_ object is a smart pointer that only gets created once, during the first setProblem() call.  To save storage, if the linear problem is unpreconditioned or right-preconditioned, the PR0_ pointer is pointed to the R0_ object.  If the same linear problem object is then used with a left preconditioner, then R0_ will also become the preconditioned residual during the next call to setProblem() just because the PR0_ is not recreated if it is not Teuchos::null in the setProblem() call.

I can have you add a line to the setLeftPrec call that will delete PR0_ if it is equal to R0_ and the user is setting a left preconditioner.  That would help us determine if this hypothesis is correct.

Does that make sense?

Thanks,
Heidi

## 

Heidi K. Thornquist
Electrical Models & Simulation
Sandia National Laboratories
Albuquerque, NM  87185-1323

**Comment by rsmedleystevenson** [comment]
I use left preconditioning each time I solve the system (this stays fixed), rather than changing the side of the preconditioning between solves.

I've just changed the code to destroy the LinearProblem object between solves and the issue goes away, so it must be related to re-using the LinearProblem object (the SolverManager and Preconditioner were already being destroyed between solves).

I have to destroy both the LinearProblem and the SolverManager, as destroying just one of these leads to the issue.

**Comment by rsmedleystevenson** [comment]
I was calling setProblem on the LinearProblem object prior to setting the preconditioner and I think this was the cause of the error. Moving this to after setting the preconditioner makes the issue go away.

I think this is the true source of the issue, which comes down to a mixture of user error :-) and differences between the internal workings of the PseudoBlockCG and RCG solver.

Heidi, I'd suggest you close the Trilinos ticket assuming you're happy with this explanation, unless you have a suggestion for how the code could be modified to prevent this re-occurring?

**Comment by hkthorn** [comment]
[I was writing this before I got your reply]

Great, that's a valuable piece of information.   I think that you are calling setProblem before the left preconditioner is being set in the LinearProblem object.  Do you have access to the BelosLinearProblem.hpp file such that you can change it, like in a local installation?  If you can, I would like to have you modify a line in that file and see if that takes care of the issue.  If possible, please modify the if statement on line 870 with (PR0_==R0_):

869     if (LP_!=Teuchos::null) {

870\*      if (PR0_==Teuchos::null || (PR0_==R0_) || (MVT::GetNumberVecs(_PR0_)!=MVT::GetNumberVecs(_B_))) {

871         PR0_ = MVT::Clone( *B_, MVT::GetNumberVecs( *B_ ) );

872       }

...

882     }

If it's not possible, let me know and I'll just test out the idea on my side.

Thanks!
Heidi

## 

Heidi K. Thornquist
Electrical Models & Simulation
Sandia National Laboratories
Albuquerque, NM  87185-1323

**Comment by rsmedleystevenson** [comment]
Just tried your suggestion and as expected it does also fix the issue, so it's definitely the fact that R0_ and PR0_ point to the same object when we call setProblem (prior to setting the preconditioner). This then goes wrong when we try set a left preconditioner, as the two objects are pointing at each other and this leads to the wrong solution being generated.

**Comment by hkthorn** [comment]
Thank you for trying it out.  While setProblem should only be called once the operator, preconditioner, solution, and rhs vectors are all supplied, you have pointed out a potential source of errors in using Belos objects for multiple solves.  I appreciate your assistance in tracking it down.  I'll commit that small piece of logic to the LinearProblem object to address this situation for future users.

Heidi

## 

Heidi K. Thornquist
Electrical Models & Simulation
Sandia National Laboratories
Albuquerque, NM  87185-1323

**Comment by mhoemmen** [comment]
@hkthorn -- just to check, would the "small piece of logic" be the following?
1. set*Prec, setOperator, etc. mark the LinearProblem as not set
2. Belos solvers always check whether the LinearProblem is set

btw I super appreciate you taking ownership of this.

**Comment by rsmedleystevenson** [comment]
My interpretation of the logic is that if left preconditioning is detected as being enabled (after the setProblem() call), then check whether PR0_ and R0_ point to the same object and if so create a new PR0_ object. This only comes into play when we change the preconditioner after setting the problem, when iset comes back true.

**Comment by rsmedleystevenson** [comment]
Mark, I think you're suggestion might be better in practice (to invalidate the is set flag each time the preconditioner is altered), as it's much clearer what is happening and the erroneous coding in TeaLeaf would have been picked up automatically - the LinearProblem being detected as not set and an error being returned. Heidi's solution solves the root cause of the issue (the duplicated pointer), but doesn't fix the underlying inconsistencies present in the API, which allowed the incorrect calling sequence to go undetected.

**Comment by mhoemmen** [comment]
Thanks for the detailed discussion.  I've opened a Belos issue to address this: https://github.com/trilinos/Trilinos/issues/181

**Comment by hkthorn** [comment]
Actually the "small piece of logic" is:

1)  When computing the initial residual at the beginning of a solve, make sure that the PR0_ != R0_ if the linear system is left preconditioned.

I feel that 1 & 2 below would still end up leaving the same logical hole that was stepped in if setProblem is called at the wrong time, since it initializes PR0_ once and doesn't reinitialize it based on whether the problem is set.

Thanks,
Heidi

## 

Heidi K. Thornquist
Electrical Models & Simulation
Sandia National Laboratories
Albuquerque, NM  87185-1323
